services:
  mysql:
    image: mysql:8.0-debian
    container_name: MySQL
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: Yes
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:8.4.0
    container_name: Redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: MinIO
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
